main: main.cpp student.cpp
	g++ --std=c++11 -o main main.cpp
	./main
test: test_student.cpp student.cpp
	g++ --std=c++11 -o test_student test_student.cpp
	./test_student
clean:
	-rm -f *.o main test_student
